# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89ec259be17e966bd3adc8111754abe140a8b735221b037c273822d6ee4cceb497154e6aa464b1e3dcb1f9e5bfbd0bfe9a2c4800dee7154879872159b092266b

test:
  secret_key_base: 427c2cbda7127ef9e4f84da496ccdf2287125eef2fcc2a9a01c7bbd3751bbd68a75167297545e133f072ff91f01082923d540362fdc17a55e0f1b548f98ebff9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
